### ISSUE TITLE
How does it validate the license?

### ISSUE THREAD

**Issue by srlesrle** [perfaram/AU3-Licensing#1]
I see your code and great one :)
But I don't get how can I give the valid serial key.

Lets say the user hits the buy software:
I get the id of computer and they buy it and then
I need to make with php the key.

Now my question is: How to make key to be recognized by software and validated?

I understend webdeveolpment and php/mysql, but windows and that part I'm not good at it :(
So if you have any idea how can I solve this, please do :)

One of the things I love is when they enter their email in software it checks online if that is good email with computer id (to allow only one computer or max 3 computers) and if response is ok then let them use software.

**Comment by perfaram** [comment]
> I see your code and great one :)

Well actually not that much. It's not really secure, because one could simply wrap the app in a sandbox and fake the `MachineGuid` to the one the serial was actually licensed to.

> But I don't get how can I give the valid serial key.

`KeyGen.au3` generates a valid serial key, given a MachineID.

> I need to make with php the key.

Shouldn't be that hard ? According to your [resume](http://srlesrle.github.io) you're a "master" in PHP, and you say that you "understend webdeveolpment". 

You just have to reimplement the KeyGen (actually just the serial generation part, obviously not the GUI) in PHP. If you don't understand what happens in the KeyGen, I don't think you could possibly have any AutoIT application worth of being protected by a serial. And if the application you wish to protect is not written in AutoIT, this library is useless for you. Therefore, three options : either you wish to protect an app not worth of being so, or you are not really a master in PHP, or you overlooked the fact that this library in written in a language that you won't be able to use (as you can't call AutoIT from other languages).

> Now my question is: How to make key to be recognized by software and validated?

The validation part is already taken care of by the code. I'm afraid if I don't tell you you will ask me, so here is how to use it : you just have to `#include` the main file of this library, namely `license.au3`; then call `license_registered()` to check whether if there is a properly registered serial *and* if it is valid – if any of these two conditions are not met, this function will return false ; finally, you may issue a `license_warning()`, which will display a TaskDialog in which the user may choose to 1. Ignore, 2. Enter a serial, 3. Go buy one on your website. 
There's an example in this repo, called `Licensing_example.au3`, that shows how to use the library, so just go ahead and read it. As I said, if you can't understand it, it's because you're not proficient enough in AutoIT to have a good reason to use this library.

> One of the things I love is when they enter their email in software it checks online if that is good email with computer id (to allow only one computer or max 3 computers) and if response is ok then let them use software.

This would require you to maintain a database of the computed IDs your software is being used on, which not only is well outside the scope of this small AutoIT library, but also should be quite easy for you if you are a Master in MySQL (as your resume, once again, claims).
